### ISSUE TITLE
Not running on Jetty, JSR-356 support unavailable

### ISSUE THREAD

**Issue by 2efPer** [codeminders/socket.io-server-java#1]
I deployed the Servlet  on Tomcat 7.0.67.

`public class Test extends JettySocketIOServlet
{
    private static final String ANNOUNCEMENT     = "announcement";       // server to all connected clients
    private static final String CHAT_MESSAGE     = "chat message";       // broadcast to room
    private static final String WELCOME          = "welcome";            // single event sent by server to specific client
    private static final String FORCE_DISCONNECT = "force disconnect";   // client requests server to disconnect
    private static final String SERVER_BINARY    = "server binary";      // client requests server to send a binary
    private static final String CLIENT_BINARY    = "client binary";      // client sends binary
    private static final long serialVersionUID = 1L;

```
@Override
@SuppressWarnings("unchecked")
public void init(ServletConfig config) throws ServletException
{
  //  JdkOverLog4j.install();
    System.out.println("Init............");
    super.init(config);

    of("/chat").on(new ConnectionListener()
    {
        @Override
        public void onConnect(final Socket socket)
        {
            try
            {
                socket.emit(WELCOME, "Welcome to Socket.IO Chat, " + socket.getRequest().getRemoteAddr() + "!");

                socket.join("room");
            }
            catch (SocketIOException e)
            {
                e.printStackTrace();
                socket.disconnect(true);
            }

            socket.on(new DisconnectListener() {

                @Override
                public void onDisconnect(Socket socket, DisconnectReason reason, String errorMessage)
                {
                    of("/chat").emit(ANNOUNCEMENT, socket.getSession().getSessionId() + " disconnected");
                }
            });

            socket.on(CHAT_MESSAGE, new EventListener()
            {
                @Override
                public Object onEvent(String name, Object[] args, boolean ackRequested)
                {
                    System.out.println("Received chat message: " + args[0]);

                    try
                    {
                        socket.broadcast("room", CHAT_MESSAGE, socket.getId(), args[0]);
                    }
                    catch (SocketIOException e)
                    {
                        e.printStackTrace();
                    }

                    return "OK"; //this object will be sent back to the client in ACK packet
                }
            });

            socket.on(FORCE_DISCONNECT, new EventListener()
            {
                @Override
                public Object onEvent(String name, Object[] args, boolean ackRequested)
                {
                    socket.disconnect(false);
                    return null;
                }
            });

            socket.on(CLIENT_BINARY, new EventListener()
            {
                @Override
                public Object onEvent(String name, Object[] args, boolean ackRequested)
                {
                    Map map = (Map<Object, Object>)args[0];
                    InputStream is = (InputStream) map.get("buffer");
                    ByteArrayOutputStream os = new ByteArrayOutputStream();
                    try
                    {
                        ByteStreams.copy(is, os);
                        byte []array = os.toByteArray();
                        String s = "[";
                        for (byte b : array)
                            s += " " + b;
                        s += " ]";
                        System.out.println("Binary received: " + s);
                    }
                    catch (IOException e)
                    {
                        e.printStackTrace();
                    }

                    return "OK";
                }
            });

            socket.on(SERVER_BINARY, new EventListener()
            {
                @Override
                public Object onEvent(String name, Object[] args, boolean ackRequested)
                {
                    try
                    {
                        socket.emit(SERVER_BINARY,
                                new ByteArrayInputStream(new byte[] {1, 2, 3, 4}),
                                new ACKListener()
                                {
                                    @Override
                                    public void onACK(Object[] args)
                                    {
                                        System.out.println("ACK received: " + args[0]);
                                    }
                                });
                    }
                    catch (SocketIOException e)
                    {
                        socket.disconnect(true);
                    }

                    return null;
                }
            });
        }
    });
}
```

}`

Here is my web.xml:

`  <servlet>

```
<servlet-name>Test</servlet-name>
<servlet-class>test.Test</servlet-class>
```

  </servlet>

  <servlet-mapping>

```
<servlet-name>Test</servlet-name>
<url-pattern>/socket.io/*</url-pattern>
```

  </servlet-mapping>`

When I start up the Tomcat :  

> javax.servlet.ServletException: Not running on Jetty, JSR-356 support unavailable
>     at org.eclipse.jetty.websocket.jsr356.server.deploy.WebSocketServerContainerInitializer.onStartup(WebSocketServerContainerInitializer.java:146)
>     at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5580)
>     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
>     at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1574)
>     at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1564)
>     at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
>     at java.util.concurrent.FutureTask.run(Unknown Source)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>     at java.lang.Thread.run(Unknown Source)

....I hava no idea why , Anyone knows?

**Comment by birdowl** [comment]
The library is not designed to work on Tomcat servlet container. It was designed to work with Jetty 9+ webserver and its websocket implementation. In order to make it work on Tomcat you need to add special extension module, similar to 'extensions.jetty'. 

I'm going to work on Tomcat support for the library in the nearest future.

**Comment by 2efPer** [comment]
Eventually I Used Atmosphere-extension for socketIO,It looks like fine by now. 
Thank you for your assistance,and I'm looking forward to your update

**Comment by BHunter2889** [comment]
Has any work been done in the last year on this issue? Also, I haven't dived in yet so how would I go about applying the aforementioned Atmosphere-extension to this?

**Comment by birdowl** [comment]
We are working on this right now. I expect to have Tomcat support ready in some form in couple of weeks

**Comment by birdowl** [comment]
Now it works on any JSR-356 container, Tomcat included. Thanks to @alexsaveliev
