### ISSUE TITLE
Expected binary marker in the payload

### ISSUE THREAD

**Issue by funkyjive** [codeminders/socket.io-server-java#2]
This issue might be an issue with socket.io itself, but I have only ever produced it using socket.io-server-java.   It can be recreated using the chat sample that comes with this code.  

Steps to reproduce:
  **1.** Modify chat.html so that it declares xhr polling as the transport.  This problem is specific to xhr polling (which is what I need to use for my project for various reasons) 

```
      var socket = io('http://localhost:8080/chat', {
       transports: ['polling']
//       transports: ['websocket']
       });
```
 **2.** run ChatServer
 **3.** browse to http://localhost:8080/chat.html
 **4.** put /rbinary in over and over again, while watching the log console

Sooner or later, you'll have this exception show up in the logs:
com.codeminders.socketio.server.SocketIOProtocolException: Expected binary marker in the payload
at ... EngineIOProtocol.binaryDecodePayload(EngineIOProtocol.java:299)
And the Socket.IO connection will be terminated and re-established.

There doesn't appear to be any predictability on when the communication will fail.   Sometimes it happens first, sometimes it takes a few /rbinary commands to get it to happen.

The code here is clearly where the exception occurred:
```
com.codeminders.socketio.protocol.EngineIOProtocol
public static List<EngineIOPacket> binaryDecodePayload(InputStream is)
        throws IOException
{
    ArrayList<EngineIOPacket> packets = new ArrayList<>();
    if(is.read() != 1)
        throw new SocketIOProtocolException("Expected binary marker in the payload");

}
```
I dug in a bit and I learned a few things by going through with a debugger in both Chrome and Firefox and in Java and I learned a few things.

- The binary begins with a 1 for all the request where everything works.  For the one with a problem, it will begin with a 0 (which triggers the error).

- What appears to be happening is that socket.io combines multiple sends into a single binary send.  A functional send will follow something like this:
```

[TEXT POST] 25:42/chat,["server binary"]
[TEXT POST] 42:461-/chat,4[{"_placeholder":true,"num":0}]
[BINARY POST] ÿ   (binary blob)
```
but when it goes wrong it looks something like this  (unfortunately Firefox won't let me copy directly):
```
[TEXT POST] 25:42/chat,["server binary"]
[BINARY POST] [binarystuffhere]ÿ461-/chat,0[{"_placeholder":true,"num":0}][binarystuffhere]
```
I copied the latest socket.io.js (1.7.2) down from:
      https://github.com/socketio/socket.io-client/blob/master/dist/socket.io.js
and ran with it, and it seemed to have the same problem.

Is this an issue with socket.io creating an invalid message?  Or is this an issue with socket.io-server-java not being able to parse a valid message?

**Comment by birdowl** [comment]
The Engine.IO spec says that XHR2 binary payload must start with 0

```
When XHR2 is supported, a similar principle is used, but everything is encoded directly into binary, so that it can be sent as binary over XHR. The format is the following:

<0 for string data, 1 for binary data><Any number of numbers between 0 and 9><The number 255><packet1 (first type,
then data)>[...] 
```

I'm not claiming that this is socket.io client problem. I need to see the actual problem payload first. I'll try to reproduce it in my environment.

**Comment by funkyjive** [comment]
Thanks for looking at it.   All I can get is a screenshot from Firefox because it won't let me copy the data on that failed request.  It is funny, it will copy binary data from a successful one.

![image002](https://cloud.githubusercontent.com/assets/9993735/21671710/7e6ac282-d2da-11e6-80bb-be74c2db2ba3.png)

If it is legal for socket.io to mix types, maybe that means the "content type" shouldn't be used do switch between binary and text -- instead you have to detect each packet by the leader byte?

**Comment by birdowl** [comment]
I was able to reproduce it with FireFox. It looks like I did not handle multiple payloads in one binary HTTP request properly. I'll work on the fix

**Comment by funkyjive** [comment]
I did a fix this morning and here is how I did it.  

```
static EngineIOPacket.Type decodePacketType(int packetFormat, InputStream is)
        throws IOException
{
    int i = is.read();
    if(i < 0)
        throw new SocketIOProtocolException("Unexpected end of stream");
    if(packetFormat == BINARY_FORMAT)
        return EngineIOPacket.Type.fromInt(i);
    else
        return EngineIOPacket.Type.fromInt(Integer.parseInt(String.valueOf((char)i)));
}

public final static int TEXT_FORMAT = 0;
public final static int BINARY_FORMAT = 1;
public static List<EngineIOPacket> binaryDecodePayload(InputStream is) throws IOException
{
    final ArrayList<EngineIOPacket> packets = new ArrayList<>();
    while (true)
    {
        final int packetFormat = is.read();
        if(packetFormat == -1)
            break; // end of payload stream, done
        if(packetFormat != BINARY_FORMAT && packetFormat != TEXT_FORMAT)
            throw new SocketIOProtocolException("Unknown packet format (should be 0 or 1) :" + packetFormat);
        final int len = decodePacketLength(is);
        if(len < 0) // end of payload stream, done
            break;
        if(packetFormat == BINARY_FORMAT && len == 0)
            throw new SocketIOProtocolException("Empty binary attachment");
        final EngineIOPacket.Type packetType = decodePacketType(packetFormat,is);
        byte[] data = new byte[len-1];
        readFully(is,data,0,data.length);

        switch (packetType)
        {
            case CLOSE:
                packets.add(createClosePacket());
                break;
            case PING:
                if(packetFormat == TEXT_FORMAT)
                    packets.add(createPingPacket(new String(data,"UTF-8")));
                else
                    throw new SocketIOProtocolException("No implementation for binary PING");
                break;
            case MESSAGE:
                if(packetFormat == TEXT_FORMAT)
                    packets.add(createMessagePacket(new String(data,"UTF-8")));
                else
                    packets.add(createMessagePacket(new ByteArrayInputStream(data)));
                break;
            case UPGRADE:
                packets.add(createUpgradePacket());
                break;
            case NOOP:
                packets.add(createNoopPacket());
                break;
            default:
                throw new SocketIOProtocolException("Unexpected EIO packet type: " + packetType);
        }
    }
    return packets;
}
```

**Comment by funkyjive** [comment]
At first, I went down the route of simply combining the decodePayload and binaryDecodePayload.  But quickly I realized that there are other differences about text payloads that come with a ContentType=text/plain.   So I just reworked binaryDecodePayload to be able to handle packets as well.  The quickest way to prove the fix is to put a breakpoint on the text format branch of the updated decodePacketType and then just keep sending /rbinary until the breakpoint hits ... then you can see the handling when you know you have a combined message payload.

**Comment by birdowl** [comment]
It is pretty much what I had in mind except maybe some minor stylistic things.
I need ByteStreams.readFully() instead of just readFully(), other than that it looks good.

Could you create a pull request for this fix?

**Comment by funkyjive** [comment]
I have never done a pull request before ... let me see if I can figure it out.  :)

**Comment by funkyjive** [comment]
You would certainly be welcome to just take it, modify it to your hearts content and commit it from your side.  That way you can style it the way you like it.

**Comment by birdowl** [comment]
OK. let me do this. Thank you for the fix!

**Comment by birdowl** [comment]
applied the patch with minor changes. tested in my environment

**Comment by funkyjive** [comment]
Did a final audit of the code that went in.  Looks good to me.  I wonder if we should surround:

```
byte[] data = new byte[len-1];
ByteStreams.readFully(is, data, 0, data.length);
```
with 

```
if(len > 0)
{
  byte[] data = new byte[len-1];
  ByteStreams.readFully(is, data, 0, data.length);
}
```
So that if the client happened to intersperse a text message with no body inside the same POST as binary message, we wouldn't attempt to create a byte array of size -1.   I don't know how likely that is to happen, but this might be defense against it happening.  We know that binary messages couldn't do that because of the previous check: 

```
        if(packetFormat == BINARY_FORMAT && len == 0)
            throw new SocketIOProtocolException("Empty binary attachment");
```

Just thoughts.  Thanks for your support.

**Comment by funkyjive** [comment]
Guess it would be more like this:

```
byte[] data;
if(len > 0)
{
    data = new byte[len - 1];
    ByteStreams.readFully(is, data, 0, data.length);
}
else
    data = new byte[0];
```
